/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nico
 */
public class APPOINTMENT_CONFIRMATION extends javax.swing.JFrame {

    /**
     * Creates new form APPOINTMENT_CONFIRMATION
     */
    public APPOINTMENT_CONFIRMATION() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblAppointmentType = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblAptTime = new javax.swing.JLabel();
        lblContactNumber = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblBDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblAppointmentDate = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 533));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText("Thank you! Your appointment \nhas been successfully confirmed!");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-30, 10, 800, 70);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel2.setText(" YOUR INFORMATION:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(271, 0, 212, 24);

        jLabel11.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel11.setText("Address:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 270, 80, 22);

        jLabel13.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel13.setText("Email Address:");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(360, 110, 120, 22);

        lblEmailAddress.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel3.add(lblEmailAddress);
        lblEmailAddress.setBounds(530, 110, 221, 20);

        jLabel9.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel9.setText("Type of Appointment:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(360, 150, 160, 22);

        lblAppointmentType.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel3.add(lblAppointmentType);
        lblAppointmentType.setBounds(530, 150, 210, 19);

        jLabel12.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel12.setText("Date of Appointment:");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(360, 190, 160, 22);

        jLabel14.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel14.setText("Appointment Time:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(360, 230, 150, 22);

        lblAptTime.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel3.add(lblAptTime);
        lblAptTime.setBounds(530, 230, 210, 19);

        lblContactNumber.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel3.add(lblContactNumber);
        lblContactNumber.setBounds(530, 70, 220, 19);

        jLabel8.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel8.setText("Contact Number:");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(360, 70, 150, 22);

        jLabel7.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel7.setText("Gender:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 230, 80, 22);

        lblGender.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel3.add(lblGender);
        lblGender.setBounds(100, 230, 200, 19);

        lblBDate.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel3.add(lblBDate);
        lblBDate.setBounds(100, 190, 250, 19);

        jLabel6.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel6.setText("Birth Date:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 190, 100, 22);

        jLabel5.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel5.setText("Age:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 150, 50, 22);

        lblAge.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel3.add(lblAge);
        lblAge.setBounds(100, 150, 160, 20);

        lblLastName.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel3.add(lblLastName);
        lblLastName.setBounds(100, 110, 250, 19);

        jLabel4.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel4.setText("Last Name:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 110, 110, 22);

        jLabel3.setFont(new java.awt.Font("Serif", 1, 16)); // NOI18N
        jLabel3.setText("First Name:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(10, 70, 100, 22);

        lblFirstName.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel3.add(lblFirstName);
        lblFirstName.setBounds(100, 70, 250, 19);

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(540, 340, 110, 30);

        lblAppointmentDate.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel3.add(lblAppointmentDate);
        lblAppointmentDate.setBounds(530, 190, 210, 22);

        lblAddress.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel3.add(lblAddress);
        lblAddress.setBounds(100, 270, 640, 19);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 90, 760, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 770, 490);

        jPanel4.setLayout(null);
        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 470, 820, 0);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Welcome Welcome = new Welcome();
        Welcome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(APPOINTMENT_CONFIRMATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(APPOINTMENT_CONFIRMATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(APPOINTMENT_CONFIRMATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(APPOINTMENT_CONFIRMATION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new APPOINTMENT_CONFIRMATION().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JLabel lblAddress;
    public javax.swing.JLabel lblAge;
    public javax.swing.JLabel lblAppointmentDate;
    public javax.swing.JLabel lblAppointmentType;
    public javax.swing.JLabel lblAptTime;
    public javax.swing.JLabel lblBDate;
    public javax.swing.JLabel lblContactNumber;
    public javax.swing.JLabel lblEmailAddress;
    public javax.swing.JLabel lblFirstName;
    public javax.swing.JLabel lblGender;
    public javax.swing.JLabel lblLastName;
    // End of variables declaration//GEN-END:variables
}
